remote_theme: just-the-docs/just-the-docs
title: "Конспект аналитика"
description: "Моя база знаний"
search_enabled: true
search:
  heading_level: 2
color_scheme: light
defaults:
  - scope:
      path: ""
    values:
      toc: false
